--- 
abstract: Helper for TT view. Creates the View/TT.pm and a template directory structure under MyApp/root containing templates, macros, and a base stylesheet to facilitate getting to the meat of building your app's pages sooner than later.
author: Lucas Smith <lsmith@lucas.e.smith@gmail.com>
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Helper-View-TT-Bootstrap
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst::Devel: 0
  Catalyst::View::TT: 0
version: 0.01
